### ISSUE TITLE
Internet Explorer Support

### ISSUE THREAD

**Issue by guedressel** [mtslks/node-meme-scraper#1]
Tried to run your app on my Internet Explorer Browser (Version 6 - I guess), but nothing appeared on the screen.
I only heard a little noise off the speaker and it smelled funny afterwards for some time at my desk.

Please help - wanted to test your app so badly.

**Comment by mtslks-zz** [comment]
@guedressel I suggest you try and run it on a fully specced out Mac Pro (they are only about $50k) with the Mac Pro wheels. Then it should work!

**Comment by gdressel** [comment]
Thanks for your support. Though I guess my hardware is reasonable

![My machine](https://img.cpapracticeadvisor.com/files/base/cygnus/cpa/image/2015/11/old_dell_computers_1_.5649f352a97ef.png?auto=format&w=360)

In [this talk](https://youtu.be/dQw4w9WgXcQ) they mention a similar problem - if I picked it up correctly...
